### ISSUE TITLE
Potential bug in schema

### ISSUE THREAD

**Issue by thorstenhater** [LEMS/LEMS#16]
Hi, 

from processing the xsd schema, this seemed like a potential typo:

```xml
  <xs:complexType name="Regime">

    <xs:sequence>
      <xs:element name="TimeDerivative" type="TimeDerivative" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="OnEntry" type="OnStart" minOccurs="0" maxOccurs="1"/>
      <xs:element name="OnCondition" type="OnCondition" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>

    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="initial" type="TrueOrFalse" use="optional"/>

  </xs:complexType>
```

in particular `name="OnEntry" type="OnStart"` since we have both entities defined.

**Comment by sanjayankur31** [comment]
Fixed in development now (https://github.com/LEMS/LEMS/commit/3f6c75031c932f4664a79cb9a9729206b0a0352e)

**Comment by pgleeson** [comment]
@thorstenhater Thanks for catching that. Yes, it was a typo, but an inconsequential one, as the definition/functionality of OnEntry and OnStart were the same. Have made the change just to remove this inconsistency
