### ISSUE TITLE
Set up CD for docs

### ISSUE THREAD

**Issue by sanjayankur31** [LEMS/LEMS#23]

**Comment by pgleeson** [comment]
Currently working here: https://github.com/LEMS/LEMS/blob/development/.github/workflows/docs.yml apart from last line, which I copied in from elsewhere, but not changed yet. Works when manually updating gh-pages branch with generated docs in `docgeneration/html/`. 

Should probably use the development branch of jlems so changes like this: https://github.com/LEMS/jLEMS/commit/146f06e8da8c9c648c22c189260ca7b6fb6b2bc9 are quickly reflected in docs.

**Comment by pgleeson** [comment]
Was looking at this at the same time as you @sanjayankur31 but you got there first... Working nicely now.

**Comment by sanjayankur31** [comment]
Ah, sorry about that XD

Working on integrating it with docs.neuroml.org now.
