### ISSUE TITLE
Ticket # 23167: EMS is not working. Every time a student taps her/his ID, a notification like this will appear, and it will continue to overlap the other notifications

### ISSUE THREAD

**Issue by rfpilapil** [LEMS/LEMS#32]
Link: https://erps.umin.edu.ph/tickets/23167

![Image](https://github.com/user-attachments/assets/138908c5-bec7-4a38-87ad-32a0e1023f66)

**Comment by pgleeson** [comment]
Not anything to do with us I'm afraid @rfpilapil!
¯\\\_(ツ)_/¯
